uint8 LIGHT_STATE_ON = 0 	# the signal is on
uint8 LIGHT_STATE_OFF = 1 	# the signal is off
uint8 LIGHT_STATE_BLINKING = 2  # the signal is blinking.
uint8 LIGHT_STATE_UKNOWN = 3 	# the signal state is unknown
uint8 red 			# State of red light
uint8 yellow 			# State of yellow light
uint8 green 			# State of green light


int32 visibility_history 	# visibility history 
bool ready 			# Data valid and ready
