"""autogenerated by genpy from rcll_adapter/Position3D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Position3D(genpy.Message):
  _md5sum = "b7e596c241486495c9f5b1c573c8c621"
  _type = "rcll_adapter/Position3D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 visibility_history
geometry_msgs/PoseWithCovarianceStamped pose_with_cov_stamped
================================================================================
MSG: geometry_msgs/PoseWithCovarianceStamped
# This expresses an estimated pose with a reference coordinate frame and timestamp

Header header
PoseWithCovariance pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['visibility_history','pose_with_cov_stamped']
  _slot_types = ['int32','geometry_msgs/PoseWithCovarianceStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       visibility_history,pose_with_cov_stamped

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Position3D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.visibility_history is None:
        self.visibility_history = 0
      if self.pose_with_cov_stamped is None:
        self.pose_with_cov_stamped = geometry_msgs.msg.PoseWithCovarianceStamped()
    else:
      self.visibility_history = 0
      self.pose_with_cov_stamped = geometry_msgs.msg.PoseWithCovarianceStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i3I.pack(_x.visibility_history, _x.pose_with_cov_stamped.header.seq, _x.pose_with_cov_stamped.header.stamp.secs, _x.pose_with_cov_stamped.header.stamp.nsecs))
      _x = self.pose_with_cov_stamped.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.pose_with_cov_stamped.pose.pose.position.x, _x.pose_with_cov_stamped.pose.pose.position.y, _x.pose_with_cov_stamped.pose.pose.position.z, _x.pose_with_cov_stamped.pose.pose.orientation.x, _x.pose_with_cov_stamped.pose.pose.orientation.y, _x.pose_with_cov_stamped.pose.pose.orientation.z, _x.pose_with_cov_stamped.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.pose_with_cov_stamped.pose.covariance))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pose_with_cov_stamped is None:
        self.pose_with_cov_stamped = geometry_msgs.msg.PoseWithCovarianceStamped()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.visibility_history, _x.pose_with_cov_stamped.header.seq, _x.pose_with_cov_stamped.header.stamp.secs, _x.pose_with_cov_stamped.header.stamp.nsecs,) = _struct_i3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_with_cov_stamped.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pose_with_cov_stamped.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pose_with_cov_stamped.pose.pose.position.x, _x.pose_with_cov_stamped.pose.pose.position.y, _x.pose_with_cov_stamped.pose.pose.position.z, _x.pose_with_cov_stamped.pose.pose.orientation.x, _x.pose_with_cov_stamped.pose.pose.orientation.y, _x.pose_with_cov_stamped.pose.pose.orientation.z, _x.pose_with_cov_stamped.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.pose_with_cov_stamped.pose.covariance = _struct_36d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i3I.pack(_x.visibility_history, _x.pose_with_cov_stamped.header.seq, _x.pose_with_cov_stamped.header.stamp.secs, _x.pose_with_cov_stamped.header.stamp.nsecs))
      _x = self.pose_with_cov_stamped.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.pose_with_cov_stamped.pose.pose.position.x, _x.pose_with_cov_stamped.pose.pose.position.y, _x.pose_with_cov_stamped.pose.pose.position.z, _x.pose_with_cov_stamped.pose.pose.orientation.x, _x.pose_with_cov_stamped.pose.pose.orientation.y, _x.pose_with_cov_stamped.pose.pose.orientation.z, _x.pose_with_cov_stamped.pose.pose.orientation.w))
      buff.write(self.pose_with_cov_stamped.pose.covariance.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pose_with_cov_stamped is None:
        self.pose_with_cov_stamped = geometry_msgs.msg.PoseWithCovarianceStamped()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.visibility_history, _x.pose_with_cov_stamped.header.seq, _x.pose_with_cov_stamped.header.stamp.secs, _x.pose_with_cov_stamped.header.stamp.nsecs,) = _struct_i3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_with_cov_stamped.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pose_with_cov_stamped.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pose_with_cov_stamped.pose.pose.position.x, _x.pose_with_cov_stamped.pose.pose.position.y, _x.pose_with_cov_stamped.pose.pose.position.z, _x.pose_with_cov_stamped.pose.pose.orientation.x, _x.pose_with_cov_stamped.pose.pose.orientation.y, _x.pose_with_cov_stamped.pose.pose.orientation.z, _x.pose_with_cov_stamped.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.pose_with_cov_stamped.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i3I = struct.Struct("<i3I")
_struct_7d = struct.Struct("<7d")
_struct_36d = struct.Struct("<36d")
